name: debug
on:
  pull_request:
    types: [ opened, labeled, unlabeled ]

jobs:
  debug:
    name: 🐛 debug

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: with anyof array
        uses: ./
        with:
          any_of: [major, minor]
      - name: with anyof yaml list
        uses: ./
        with:
          any_of:
            - major
            - minor